name: CI

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/ci.yml'

concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MAVEN_OPTS: -Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true

jobs:
  test-ci:
    name: Test CI - JDK 21-ea on ubuntu-latest
    runs-on: 'ubuntu-latest'
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21-ea'
      - name: Download Source and build Native Image
        run: |
          git clone -b master https://github.com/apache/shardingsphere.git
          cd ./shardingsphere/
          git reset --hard 4563afd14d23d494f75f680c47a351cdd19893db
          ./mvnw clean install -B -T1C -Dmaven.javadoc.skip -Dmaven.jacoco.skip -e
          
